name: CI

permissions: {}

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: alpine:latest
            preinstall: apk add bash coreutils curl git jq
          - container: amazonlinux:latest
            preinstall: dnf -y install git findutils jq
          - container: ubuntu:latest
            preinstall: apt-get -y update && apt-get -y install curl git jq

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Preinstall
        run: ${{ matrix.preinstall }}

      - name: Fake terraform
        run: |
          echo '#!/bin/bash' | tee /usr/local/bin/terraform
          echo 'echo Fake Terraform' | tee -a /usr/local/bin/terraform
          chmod +x /usr/local/bin/terraform

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: tf version

  macos:
    runs-on: macos-latest

    steps:
      - name: Preinstall
        run: brew install jq

      - name: Fake terraform
        run: |
          echo '#!/bin/bash' | sudo tee /usr/local/bin/terraform
          echo 'echo Fake Terraform' | sudo tee -a /usr/local/bin/terraform
          sudo chmod +x /usr/local/bin/terraform

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: tf version
